### PR TITLE
Userinfo from id token

### PR DESCRIPTION
**Pull request by ivan-c**
- Rename variables
- Use [OIDC ID token](https://auth0.com/blog/id-token-access-token-what-is-the-difference/) to look up userinfo, if available
- Use `mapProfile()` to populate `$strategy->sub`

<details>
<summary>New $strategy->auth data </summary>
<pre>
(
    [raw] => Array
        (
            [exp] => 1707855705
            [iat] => 1707855405
            [auth_time] => 1707853285
            [jti] => 5b8c730a-add0-407c-994a-20f44e6a6e24
            [iss] => https://keycloak.ltt.128.208.230.197.nip.io/realms/ltt
            [aud] => ltt_cpro
            [sub] => 8c9c31b4-0794-40ae-8d39-f7ca6c606b7c
            [typ] => ID
            [azp] => ltt_cpro
            [session_state] => 555a23f6-378d-4285-8b55-f3ef2642debe
            [at_hash] => kUtA1L7GCBxrEsn7nnynOw
            [acr] => 0
            [sid] => 555a23f6-378d-4285-8b55-f3ef2642debe
            [email_verified] => 1
            [name] => test test
            [preferred_username] => test@test.test
            [given_name] => test
            [family_name] => test
            [email] => test@test.test
        )

    [info] => Array
        (
            [id_token] => eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0WlRkcnFzc1g3aEphQUQxaU5NZFFCck94THlqZ1lnU19pWXJYTlRoMTlrIn0.eyJleHAiOjE3MDc4NTU3MDUsImlhdCI6MTcwNzg1NTQwNSwiYXV0aF90aW1lIjoxNzA3ODUzMjg1LCJqdGkiOiI1YjhjNzMwYS1hZGQwLTQwN2MtOTk0YS0yMGY0NGU2YTZlMjQiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmx0dC4xMjguMjA4LjIzMC4xOTcubmlwLmlvL3JlYWxtcy9sdHQiLCJhdWQiOiJsdHRfY3BybyIsInN1YiI6IjhjOWMzMWI0LTA3OTQtNDBhZS04ZDM5LWY3Y2E2YzYwNmI3YyIsInR5cCI6IklEIiwiYXpwIjoibHR0X2Nwcm8iLCJzZXNzaW9uX3N0YXRlIjoiNTU1YTIzZjYtMzc4ZC00Mjg1LThiNTUtZjNlZjI2NDJkZWJlIiwiYXRfaGFzaCI6ImtVdEExTDdHQ0J4ckVzbjdubnluT3ciLCJhY3IiOiIwIiwic2lkIjoiNTU1YTIzZjYtMzc4ZC00Mjg1LThiNTUtZjNlZjI2NDJkZWJlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJ0ZXN0IHRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0QHRlc3QudGVzdCIsImdpdmVuX25hbWUiOiJ0ZXN0IiwiZmFtaWx5X25hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QHRlc3QudGVzdCJ9.wLD6afQgz_w5nNstnMcDXdzAeBl16JwLXEJ3XEWxWE3VzExTmgF0nixIfJWv-TeGTR7fLlUh4s09kVPhTHq-TlfUIAyP4aW2nJV9w_5Cjldjj2kM9JQ7crqjfMaDrsNixy_7AeioprWtCU4f9g2JnjiuZcl23TxczsJkLgnWEO09gauxet_iqdmFY9nt6frdySdS4VZGbLewsmyC2ea5S9Fbv1wwrlmGa4HVQrDtm692JzFYo6FC6fdk16IiKTWohKrKr_Uwi5oX7iDuRIuHpy6XPWJ5ZKGeWV-OJ9gpd_ImhEDraSJZ9dEgQ-9-vSamIsjSr041tqks7yjijaxNIg
        )

    [credentials] => Array
        (
            [token] => eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI0WlRkcnFzc1g3aEphQUQxaU5NZFFCck94THlqZ1lnU19pWXJYTlRoMTlrIn0.eyJleHAiOjE3MDc4NTU3MDUsImlhdCI6MTcwNzg1NTQwNSwiYXV0aF90aW1lIjoxNzA3ODUzMjg1LCJqdGkiOiI3ZTYyMjAzZC1iMzI4LTQ2MzEtOGQ2Mi1lYmNkN2Q0N2I3MTMiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmx0dC4xMjguMjA4LjIzMC4xOTcubmlwLmlvL3JlYWxtcy9sdHQiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiOGM5YzMxYjQtMDc5NC00MGFlLThkMzktZjdjYTZjNjA2YjdjIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoibHR0X2Nwcm8iLCJzZXNzaW9uX3N0YXRlIjoiNTU1YTIzZjYtMzc4ZC00Mjg1LThiNTUtZjNlZjI2NDJkZWJlIiwiYWNyIjoiMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1sdHQiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwic2lkIjoiNTU1YTIzZjYtMzc4ZC00Mjg1LThiNTUtZjNlZjI2NDJkZWJlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJ0ZXN0IHRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0QHRlc3QudGVzdCIsImdpdmVuX25hbWUiOiJ0ZXN0IiwiZmFtaWx5X25hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QHRlc3QudGVzdCJ9.oHIlZm7Gn7IQrEt8Y6cmYKmmkO2d8pkgnM1z1ibzjesJ-PCJfhy5yOry8TjTf_qC6El9hTnfcOPO-p4s2WZDcjhFVPkiB4andjsczhIgbuiTHIPNs9S9DvMfjd5wrqwCWzv67bW05Da-ZG_PWq_f-pzUJ_uLM7Z06bUZ6U1W4N2jjKku_TiQjV149NihpGWvhDa1F2BSaQzYOokdeMDV5IiFBNNwwbMGbZPO7OuV_ffFDEai8C2Qk1JaiLtKvuv974glnYqWuiCwBM4zQkadC2g_z8bSmR3lO6EXFPxTyVvP7hOWHScU4uRbTZqyVbZCCT7wjoLT-jf5zwUAiWvLeA
            [expires] => 2024-02-13T20:21:45+00:00
            [refresh_token] => eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMzgwM2EwYy0yM2JlLTQ5YmQtODNmMy0yZGExZDJjY2MzMjQifQ.eyJleHAiOjE3MDc4NTcyMDQsImlhdCI6MTcwNzg1NTQwNSwianRpIjoiYWY5N2JmYWItYzk3My00YmY0LWIzODUtNjBkNTVjNjQ4NmQ4IiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay5sdHQuMTI4LjIwOC4yMzAuMTk3Lm5pcC5pby9yZWFsbXMvbHR0IiwiYXVkIjoiaHR0cHM6Ly9rZXljbG9hay5sdHQuMTI4LjIwOC4yMzAuMTk3Lm5pcC5pby9yZWFsbXMvbHR0Iiwic3ViIjoiOGM5YzMxYjQtMDc5NC00MGFlLThkMzktZjdjYTZjNjA2YjdjIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6Imx0dF9jcHJvIiwic2Vzc2lvbl9zdGF0ZSI6IjU1NWEyM2Y2LTM3OGQtNDI4NS04YjU1LWYzZWYyNjQyZGViZSIsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiI1NTVhMjNmNi0zNzhkLTQyODUtOGI1NS1mM2VmMjY0MmRlYmUifQ.ocQG09480qTlr4Gy8G7yy1EU4cw8UkMijvYmtloQyzg
        )

    [sub] => 8c9c31b4-0794-40ae-8d39-f7ca6c606b7c
    [name] => test test
    [given_name] => test
    [family_name] => test
    [email_verified] => 1
)

</pre>
</details>

### CODE REVIEW

**Comment by mcjustin** [comment]
@ivan-c  in my testing today OidcStrategy is always returning [data][validated] as empty, but OAuthAuthenticate expects it to be set "After a roundtrip to the IdP via opauth, double check 'validated'" per https://gitlab.cirg.washington.edu/svn/dhair2/-/blob/master/app/Controller/Component/Auth/OAuthAuthenticate.php#L36 . 

Yesterday I was getting past that check okay, but as I retest using either this new branch or [my debug](https://github.com/uwcirg/opauth-oidc/tree/debug-mcjustin), `validated` is always empty. Any ideas?

**Comment by mcjustin** [comment]
> @ivan-c in my testing today OidcStrategy is always returning [data][validated] as empty, but OAuthAuthenticate expects it to be set "After a roundtrip to the IdP via opauth, double check 'validated'" per https://gitlab.cirg.washington.edu/svn/dhair2/-/blob/master/app/Controller/Component/Auth/OAuthAuthenticate.php#L36 .
> 
> Yesterday I was getting past that check okay, but as I retest using either this new branch or [my debug](https://github.com/uwcirg/opauth-oidc/tree/debug-mcjustin), `validated` is always empty. Any ideas?

@ivan-c  per our call just now, I've committed my current changes to https://gitlab.cirg.washington.edu/svn/dhair2/-/merge_requests/742

**Comment by mcjustin** [comment]
> > @ivan-c in my testing today OidcStrategy is always returning [data][validated] as empty, but OAuthAuthenticate expects it to be set "After a roundtrip to the IdP via opauth, double check 'validated'" per https://gitlab.cirg.washington.edu/svn/dhair2/-/blob/master/app/Controller/Component/Auth/OAuthAuthenticate.php#L36 .
> > Yesterday I was getting past that check okay, but as I retest using either this new branch or [my debug](https://github.com/uwcirg/opauth-oidc/tree/debug-mcjustin), `validated` is always empty. Any ideas?
> 

@ivan-c  I dug around a bit... afaict `validated` does not refer to model validation, but to a state in the auth flow.

**Comment by ivan-c** [comment]
>I've committed my current changes to https://gitlab.cirg.washington.edu/svn/dhair2/-/merge_requests/742

@mcjustin 
Thanks! From your logging, `invalid_auth_missing_components` caught my eye and I was able to [find the failing check in the OpAuth code](https://github.com/uzyn/cakephp-opauth/blob/1.0.8/Controller/OpauthAppController.php#L84-L91).

>Yesterday I was getting past that check okay, but as I retest using either this new branch or my debug, validated is always empty. Any ideas?
>I dug around a bit... afaict validated does not refer to model validation, but to a state in the auth flow.

Thanks for the pointers, from them I was able to figure out OpAuth **requires** `uid` to be set by a strategy to set `validated`. I pushed a fix that changes the strategy to it always returns `sub` as `uid` (e7114d3), if you want to re-test

**Comment by mcjustin** [comment]
See also chatter at https://github.com/uwcirg/opauth-oidc/pull/1 , which informed this approach.

**Comment by mcjustin** [comment]
@ivan-c  can you include the KC roles here as well? You mentioned these at https://www.pivotaltracker.com/story/show/186367734/comments/239958361 sorry to have not raised it again sooner 😬 ...

**Comment by ivan-c** [comment]
>can you include the KC roles here as well?

@mcjustin 

Done! 

There were some cautionary advice about ID vs access tokens, so I added it as a separate PR: #4 

I'd understand the usescases around roles better; we've used keycloak roles before but each approach we've tried has had issues

**Comment by ivan-c** [comment]
@mcjustin planning on merging this PR before our weekly LTT meeting

**Pull request merged**
