### PR TITLE
OidcStrategy.php: write userinfo array to debug log

### PR DESCRIPTION
**Pull request by mcjustin**

### CODE REVIEW

**Comment by mcjustin** [comment]
1/2 
@ivan-c  I tried to bring this in via composer but wasn't able to. Can you show me how to do this sometime? I clearly don't understand composer aliases...

```
mcjustin@unbiunium:~/dhair2forltt
$ gitdiff
diff --git a/composer-php5.json b/composer-php5.json
index 2d47b916e..dc2128528 100644
--- a/composer-php5.json
+++ b/composer-php5.json
@@ -17,6 +17,7 @@
         "composer/installers": ">=1.5.0",
         "cakephp/cakephp": "2.10.20",
         "aws/aws-sdk-php": "^3.185"
+        "opauth/oidc": "dev-debug-mcjustin"
     },
     "suggest": {
         "ext-imagick": "*",
diff --git a/docker/Dockerfile.php5 b/docker/Dockerfile.php5
index 1571ccb9c..8c4d14a34 100644
--- a/docker/Dockerfile.php5
+++ b/docker/Dockerfile.php5
@@ -120,7 +120,8 @@ RUN \
 RUN composer require --no-ansi --verbose \
         uzyn/cakephp-opauth:* \
         opauth/truenth:* \
-        opauth/oidc:*
+        opauth/oidc:dev-debug-mcjustin
+        #opauth/oidc:*

```

**Comment by mcjustin** [comment]
2/2 My thinking here was:

Recall that AE assigns the User the same id that it got from the portal.

https://github.com/uwcirg/opauth-truenth/blob/master/TruenthStrategy.php#L124
does:
```
                $this->auth = array(
                    'uid' => $userinfo['id'],
```
					
And that 'uid' somehow ends up in $this->Auth->user('id'), as used by the AppController (tho I can't find where this is done, looking across TruenthStrategy and OpauthStrategy...).

I'd like to try adding 'uid' to https://github.com/uwcirg/opauth-oidc/blob/main/OidcStrategy.php ... not that I'm a fan of magic.

**Comment by ivan-c** [comment]
>I tried to bring this in via composer but wasn't able to. Can you show me how to do this sometime? I clearly don't understand composer aliases...

@mcjustin 

Sorry I didn't say anything, but I was using an additional bind-mount in docker-compose to override `OidcStrategy.php` from yet another git checkout (see below). I didn't mention it because I didn't think we'd need to make any further changes to the `OidcStrategy.php`

```
diff --git a/dev/docker-compose.dev.cpro.yaml b/dev/docker-compose.dev.cpro.yaml
index 18a10e5..c183bb3 100644
--- a/dev/docker-compose.dev.cpro.yaml
+++ b/dev/docker-compose.dev.cpro.yaml
@@ -38,3 +38,4 @@ services:
  
       # Enable developer only overrides
       - ${CPRO_CHECKOUT_DIR}/docker/config/php/cpro.dev.ini:/etc/php/5.6/apache2/conf.d/cpro.dev.ini
+      - /home/ivanc/src/cirg/opauth-oidc/OidcStrategy.php:/var/www/html/app/Vendor/opauth/oidc/OidcStrategy.php
```

I've never tried using composer to install a specific branch from VCS, but I didn't see any issues with your Dockerfile/composer files [vs the composer docs](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)

---

> I'd like to try adding 'uid' to https://github.com/uwcirg/opauth-oidc/blob/main/OidcStrategy.php ... not that I'm a fan of magic.

That sounds like a good quick test, without having to trace the TN/opauth code. Since keycloak (OIDC) doesn't return a numeric user ID, I'd try mapping `email` to `uid`

It's not an immediate problem, but I was a little worried about tracking users who've changed their email. However, apparently [OIDC uses the `sub` claim in id token (JWT) to identify the user](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims#registered-claims). I reviewed [an id token from keycloak](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnV1dRZjJ6ckRlVFJ0TXkwNFJnZGFIV1ZOUHJPNXpPOWxuVlV5aDJsbVNFIn0.eyJleHAiOjE3MDcxOTU1MjYsImlhdCI6MTcwNzE5NTIyNiwiYXV0aF90aW1lIjoxNzA3MTk1MjI1LCJqdGkiOiI1MmZhYzQ0My00MDg5LTRkODEtOTdjMy02YjA0N2NkYWNiNjQiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmx0dC4xMjguMjA4LjIzMC4xOTcubmlwLmlvL3JlYWxtcy9sdHQiLCJhdWQiOiJsdHRfY3BybyIsInN1YiI6ImVlODFlZTNiLTZlZmQtNDIyMC1iMjU3LTI5ODEzM2NjY2I4YiIsInR5cCI6IklEIiwiYXpwIjoibHR0X2Nwcm8iLCJzZXNzaW9uX3N0YXRlIjoiYzdkMjYyZWMtMWY2NS00NzlhLWFhZDYtYWFkZTJlODJiNzI5IiwiYXRfaGFzaCI6Iml0ZDdENDdFNVdyQ0VkbUJ3TzhCV2ciLCJhY3IiOiIxIiwic2lkIjoiYzdkMjYyZWMtMWY2NS00NzlhLWFhZDYtYWFkZTJlODJiNzI5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJ0ZXN0IHRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0IiwiZ2l2ZW5fbmFtZSI6InRlc3QiLCJmYW1pbHlfbmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC50ZXN0In0.mgJCB9bn3BhZdSg7Kcv2_mo6w4uvD0akA1b2a_rFLOYfAcinWzO4CVuIfHNHP2_AYLMudzBzBGROSsn1AIgNpJDa1IPBBTRtD5_OlE79dgrhRgI_imyYEOUA7X1X2NCS20MVkCKXf_sRaG2Jmqdmj68Xq7IhZmQf_eyBCs3am4eTL5xLXembyUhE2uhQUuaT1i39XMZ1WNbKdHa5UHWYMo0Vdh3IklVWiy9ghXNS4mKw_fDmtoPgHmtRlMr8BdxX108YTJHBhs9ipy-vpuTBvBy5VPVUe9sO2THDyQ_DdSpj1HjqGgmIpoyrDwfqCcv-i6sIxmCFfTGlou2roK9LIA&publicKey=%7B%0A%20%20%22e%22%3A%20%22AQAB%22%2C%0A%20%20%22kty%22%3A%20%22RSA%22%2C%0A%20%20%22n%22%3A%20%22sOuJhQA84VsrRBoio5dDBk4X5LP85FxdriXjAl_eqZY2AbpVJVIAbH54O01Mz-Df4-f6fdVYnAfK_zIG7py8uedDIOGdgU2b3F7UIZ_zb86OJ-XZwJjYmZ2za83K1EwD6VSyJy0sIydleP3t5KkwN2UKz0-Rwe0AwKPbvR3whscPt8TB2bJTayGbSAa4Mx8M5UGM0uTbrBITMUeST7NCOd0c2miPkzTrXq61c20GWnBQmF1UWIbzQ_0gz5o6GDizNFdTfglBLBIa-HYZRra6fWtYl5Qh5KjVjdRC113OpmOzaOWKgy2VOQsqgSYWbp-j8fTuC5FpkoOFHJ7DbS6_ww%22%0A%7D) and it does in fact map to a user id (UUID) in the keycloak admin UI

**Comment by mcjustin** [comment]
> > I'd like to try adding 'uid' to https://github.com/uwcirg/opauth-oidc/blob/main/OidcStrategy.php ... not that I'm a fan of magic.
> 
> That sounds like a good quick test, without having to trace the TN/opauth code. Since keycloak (OIDC) doesn't return a numeric user ID, I'd try mapping `email` to `uid`
> 
> It's not an immediate problem, but I was a little worried about tracking users who've changed their email. However, apparently [OIDC uses the `sub` claim in id token (JWT) to identify the user](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims#registered-claims). I reviewed [an id token from keycloak](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnV1dRZjJ6ckRlVFJ0TXkwNFJnZGFIV1ZOUHJPNXpPOWxuVlV5aDJsbVNFIn0.eyJleHAiOjE3MDcxOTU1MjYsImlhdCI6MTcwNzE5NTIyNiwiYXV0aF90aW1lIjoxNzA3MTk1MjI1LCJqdGkiOiI1MmZhYzQ0My00MDg5LTRkODEtOTdjMy02YjA0N2NkYWNiNjQiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmx0dC4xMjguMjA4LjIzMC4xOTcubmlwLmlvL3JlYWxtcy9sdHQiLCJhdWQiOiJsdHRfY3BybyIsInN1YiI6ImVlODFlZTNiLTZlZmQtNDIyMC1iMjU3LTI5ODEzM2NjY2I4YiIsInR5cCI6IklEIiwiYXpwIjoibHR0X2Nwcm8iLCJzZXNzaW9uX3N0YXRlIjoiYzdkMjYyZWMtMWY2NS00NzlhLWFhZDYtYWFkZTJlODJiNzI5IiwiYXRfaGFzaCI6Iml0ZDdENDdFNVdyQ0VkbUJ3TzhCV2ciLCJhY3IiOiIxIiwic2lkIjoiYzdkMjYyZWMtMWY2NS00NzlhLWFhZDYtYWFkZTJlODJiNzI5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJ0ZXN0IHRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0IiwiZ2l2ZW5fbmFtZSI6InRlc3QiLCJmYW1pbHlfbmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC50ZXN0In0.mgJCB9bn3BhZdSg7Kcv2_mo6w4uvD0akA1b2a_rFLOYfAcinWzO4CVuIfHNHP2_AYLMudzBzBGROSsn1AIgNpJDa1IPBBTRtD5_OlE79dgrhRgI_imyYEOUA7X1X2NCS20MVkCKXf_sRaG2Jmqdmj68Xq7IhZmQf_eyBCs3am4eTL5xLXembyUhE2uhQUuaT1i39XMZ1WNbKdHa5UHWYMo0Vdh3IklVWiy9ghXNS4mKw_fDmtoPgHmtRlMr8BdxX108YTJHBhs9ipy-vpuTBvBy5VPVUe9sO2THDyQ_DdSpj1HjqGgmIpoyrDwfqCcv-i6sIxmCFfTGlou2roK9LIA&publicKey=%7B%0A%20%20%22e%22%3A%20%22AQAB%22%2C%0A%20%20%22kty%22%3A%20%22RSA%22%2C%0A%20%20%22n%22%3A%20%22sOuJhQA84VsrRBoio5dDBk4X5LP85FxdriXjAl_eqZY2AbpVJVIAbH54O01Mz-Df4-f6fdVYnAfK_zIG7py8uedDIOGdgU2b3F7UIZ_zb86OJ-XZwJjYmZ2za83K1EwD6VSyJy0sIydleP3t5KkwN2UKz0-Rwe0AwKPbvR3whscPt8TB2bJTayGbSAa4Mx8M5UGM0uTbrBITMUeST7NCOd0c2miPkzTrXq61c20GWnBQmF1UWIbzQ_0gz5o6GDizNFdTfglBLBIa-HYZRra6fWtYl5Qh5KjVjdRC113OpmOzaOWKgy2VOQsqgSYWbp-j8fTuC5FpkoOFHJ7DbS6_ww%22%0A%7D) and it does in fact map to a user id (UUID) in the keycloak admin UI

@ivan-c  I'm finding that if I do assign `uid` in the strategy as an int, the user is indeed created in dhair2 w/ id = that `uid`. I used a hard-coded int, since user.id is an int. Will dig further...

**Comment by mcjustin** [comment]
> > > I'd like to try adding 'uid' to https://github.com/uwcirg/opauth-oidc/blob/main/OidcStrategy.php ... not that I'm a fan of magic.
> > 
> > 
> > That sounds like a good quick test, without having to trace the TN/opauth code. Since keycloak (OIDC) doesn't return a numeric user ID, I'd try mapping `email` to `uid`
> > It's not an immediate problem, but I was a little worried about tracking users who've changed their email. However, apparently [OIDC uses the `sub` claim in id token (JWT) to identify the user](https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims#registered-claims). I reviewed [an id token from keycloak](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnV1dRZjJ6ckRlVFJ0TXkwNFJnZGFIV1ZOUHJPNXpPOWxuVlV5aDJsbVNFIn0.eyJleHAiOjE3MDcxOTU1MjYsImlhdCI6MTcwNzE5NTIyNiwiYXV0aF90aW1lIjoxNzA3MTk1MjI1LCJqdGkiOiI1MmZhYzQ0My00MDg5LTRkODEtOTdjMy02YjA0N2NkYWNiNjQiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLmx0dC4xMjguMjA4LjIzMC4xOTcubmlwLmlvL3JlYWxtcy9sdHQiLCJhdWQiOiJsdHRfY3BybyIsInN1YiI6ImVlODFlZTNiLTZlZmQtNDIyMC1iMjU3LTI5ODEzM2NjY2I4YiIsInR5cCI6IklEIiwiYXpwIjoibHR0X2Nwcm8iLCJzZXNzaW9uX3N0YXRlIjoiYzdkMjYyZWMtMWY2NS00NzlhLWFhZDYtYWFkZTJlODJiNzI5IiwiYXRfaGFzaCI6Iml0ZDdENDdFNVdyQ0VkbUJ3TzhCV2ciLCJhY3IiOiIxIiwic2lkIjoiYzdkMjYyZWMtMWY2NS00NzlhLWFhZDYtYWFkZTJlODJiNzI5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJ0ZXN0IHRlc3QiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZXN0IiwiZ2l2ZW5fbmFtZSI6InRlc3QiLCJmYW1pbHlfbmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC50ZXN0In0.mgJCB9bn3BhZdSg7Kcv2_mo6w4uvD0akA1b2a_rFLOYfAcinWzO4CVuIfHNHP2_AYLMudzBzBGROSsn1AIgNpJDa1IPBBTRtD5_OlE79dgrhRgI_imyYEOUA7X1X2NCS20MVkCKXf_sRaG2Jmqdmj68Xq7IhZmQf_eyBCs3am4eTL5xLXembyUhE2uhQUuaT1i39XMZ1WNbKdHa5UHWYMo0Vdh3IklVWiy9ghXNS4mKw_fDmtoPgHmtRlMr8BdxX108YTJHBhs9ipy-vpuTBvBy5VPVUe9sO2THDyQ_DdSpj1HjqGgmIpoyrDwfqCcv-i6sIxmCFfTGlou2roK9LIA&publicKey=%7B%0A%20%20%22e%22%3A%20%22AQAB%22%2C%0A%20%20%22kty%22%3A%20%22RSA%22%2C%0A%20%20%22n%22%3A%20%22sOuJhQA84VsrRBoio5dDBk4X5LP85FxdriXjAl_eqZY2AbpVJVIAbH54O01Mz-Df4-f6fdVYnAfK_zIG7py8uedDIOGdgU2b3F7UIZ_zb86OJ-XZwJjYmZ2za83K1EwD6VSyJy0sIydleP3t5KkwN2UKz0-Rwe0AwKPbvR3whscPt8TB2bJTayGbSAa4Mx8M5UGM0uTbrBITMUeST7NCOd0c2miPkzTrXq61c20GWnBQmF1UWIbzQ_0gz5o6GDizNFdTfglBLBIa-HYZRra6fWtYl5Qh5KjVjdRC113OpmOzaOWKgy2VOQsqgSYWbp-j8fTuC5FpkoOFHJ7DbS6_ww%22%0A%7D) and it does in fact map to a user id (UUID) in the keycloak admin UI
> 
> @ivan-c I'm finding that if I do assign `uid` in the strategy as an int, the user is indeed created in dhair2 w/ id = that `uid`. I used a hard-coded int, since user.id is an int. Will dig further...


Found where we read `uid` and create the user (don't know how I missed it before...): https://gitlab.cirg.washington.edu/svn/dhair2/-/blob/master/app/Controller/Component/Auth/OAuthAuthenticate.php#L128 

Next for me: think about using email there instead...

**Comment by mcjustin** [comment]
> Found where we read `uid` and create the user (don't know how I missed it before...): https://gitlab.cirg.washington.edu/svn/dhair2/-/blob/master/app/Controller/Component/Auth/OAuthAuthenticate.php#L128
> 
> Next for me: think about using email there instead...

I see `sub` coming from KC (unique user ID in KC) and now that I read your earlier note more closely, I'm aiming to use that instead of email address. Aiming to hash it to user.id which is int(11) - seems safe enough, numbers-wise.

**Comment by ivan-c** [comment]
>I see sub coming from KC (unique user ID in KC) and now that I read your earlier note more closely, I'm aiming to use that instead of email address. 

@mcjustin 

I wasn't sure we would be using the `sub` claim, so I didn't extract those from the JWT and make them available. I'll put together a PR for the OIDC strategy that decodes and returns all the data in the ID token (JWT)

>Aiming to hash it to user.id which is int(11) - seems safe enough, numbers-wise.

Is it possible to reuse `users.external_id` to directly store the keycloak user identifier (ie `sub`/email/username)?

Keeping the keycloak identifier unhashed would making debugging easier, and  Bill's mantra "don't use identifiers as primary keys" does seem to apply here

**Comment by mcjustin** [comment]
> > I see sub coming from KC (unique user ID in KC) and now that I read your earlier note more closely, I'm aiming to use that instead of email address.
> 
> @mcjustin
> 
> I wasn't sure we would be using the `sub` claim, so I didn't extract those from the JWT and make them available. I'll put together a PR for the OIDC strategy that decodes and returns all the data in the ID token (JWT)
> 
> > Aiming to hash it to user.id which is int(11) - seems safe enough, numbers-wise.
> 
> Is it possible to reuse `users.external_id` to directly store the keycloak user identifier (ie `sub`/email/username)?
> 
> Keeping the keycloak identifier unhashed would making debugging easier, and Bill's mantra "don't use identifiers as primary keys" does seem to apply here

@ivan-c  sounds good on both accounts. I've started on modified versions of `User->` `save` & `find` that I can call from `OAuthAuthenticate` when I see that info in the request.

**Comment by mcjustin** [comment]
> > > I see sub coming from KC (unique user ID in KC) and now that I read your earlier note more closely, I'm aiming to use that instead of email address.
> > 
> > 
> > @mcjustin
> > I wasn't sure we would be using the `sub` claim, so I didn't extract those from the JWT and make them available. I'll put together a PR for the OIDC strategy that decodes and returns all the data in the ID token (JWT)
> > > Aiming to hash it to user.id which is int(11) - seems safe enough, numbers-wise.
> > 
> > 
> > Is it possible to reuse `users.external_id` to directly store the keycloak user identifier (ie `sub`/email/username)?
> > Keeping the keycloak identifier unhashed would making debugging easier, and Bill's mantra "don't use identifiers as primary keys" does seem to apply here
> 
> @ivan-c sounds good on both accounts. I've started on modified versions of `User->` `save` & `find` that I can call from `OAuthAuthenticate` when I see that info in the request.

@ivan-c  OAuthAuthenticate.php is currently looking for `$request->data['auth']['uid']`. Where in `$request->data` do you intend to add the `sub` from the JWT?

**Comment by ivan-c** [comment]
>OAuthAuthenticate.php is currently looking for $request->data['auth']['uid']. Where in $request->data do you intend to add the sub from the JWT?

@mcjustin 
Sorry I was incorrect. In implementing [reading the OIDC id token for userinfo](https://github.com/uwcirg/opauth-oidc/pull/2), I realized [the keycloak userinfo endpoint already returns `sub`](https://github.com/uwcirg/opauth-oidc/blob/d8e73ac11e06e99bfc97d8da0c787130fc31badf/OidcStrategy.php#L98) (without needing to decode the JWT).

I'm not sure how OAuthAuthenticate gets the controller/opauth data, but judging from how `uid` is used, the `sub` (keycloak user id) would be at   `$request->data['auth']['sub']`

**Comment by mcjustin** [comment]
@ivan-c  I'm going to close this PR. We had some important convos here - I'll add a mention from https://github.com/uwcirg/opauth-oidc/pull/2

**Pull request closed without merging**
